### PR TITLE
Milestone1: Project Setup

### PR DESCRIPTION
**Pull request by realisticattorney**
Milestones were:

Use create-react-app to initialize a new React app
Delete any unnecessary file or asset
Add prop-types using npm for typechecking props.
Add big.js using npm.
Run the application with npm start and make sure that everything works correctly.
Create a Heroku app
Commit and deploy to Heroku
Make sure the Heroku app works correctly

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, @realisticattorney 👋🏾 great job on this milestone. You have met most of the requirements needed for this project. However, let's work on the following

- [ ] In React apps, App.js is an important file, It is the main component that acts as a container for all other components. For example, this is where you will render "Calculator React" then call App.js in the index.js file. Kindly work on this.

That's all, Kindly submit another review when done 😄 

If you have any questions tag my name (@mimipeshy) in the comment section and I will be glad to help.

Regards,
Peris Ndanu

**Comment by realisticattorney** [comment]
Use create-react-app to initialize a new React app
Documentation: https://github.com/facebook/create-react-app
Delete any unnecessary file or asset
Add prop-types using npm for typechecking props.
Add big.js using npm.
Run the application with npm start and make sure that everything works correctly.
Follow the instructions in create-react-app-buildpack to deploy the app to Heroku
Initialize a git repo
Create a Heroku app
Commit and deploy to Heroku
Make sure the Heroku app works correctly
Push everything to Github
Documentation: https://github.com/mars/create-react-app-buildpack



Do you see anything related to adding App.js? I don't. It's not part of this milestone

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello there again, I have explained why it's a necessary file to have. App.js is automatically created when using create-react-app. It wasn't created by mistake.  Kindly work on those changes and resubmit your work. I cannot approve your work without it.


That's all, Kindly submit another review when done 😄 

If you have any questions tag my name (@mimipeshy) in the comment section and I will be glad to help.

Regards,
Peris Ndanu

**Comment by realisticattorney** [comment]
The file doesn't need to be called App.js, what's a default feature is the App component and that's already in the index.js file.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 😄 

Hello again @realisticattorney 👋🏾 I have seen your point therefore I will approve your project, go ahead and merge. All the best in the next milestones. Happy Coding 💻 🖱️ 

Regards
Peris Ndanu

**Pull request merged**
